# Generated by Django 4.2.4 on 2024-09-04 12:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='albumimage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album_image_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='album',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='albums', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='albumimage',
            index=models.Index(fields=['image'], name='album_image_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['name'], name='album_name_idx'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['user'], name='album_user_idx'),
        ),
        migrations.AddConstraint(
            model_name='album',
            constraint=models.UniqueConstraint(fields=('name', 'user'), name='unique_name_user'),
        ),
    ]
